name: CI/CD

on:
 workflow_dispatch: 

jobs:
 qa-automation-api:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2 

    - name: Install dependencies
      run: |
        npm i 

    - name: Run tests
      run: |
        npm test  

    - name: Run tests
      run: |
        npm run report  

    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: | 
             ./reports/cucumber_report.json
             ./reports/cucumber_report.html
