name: CI/CD

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Choose the OS for the workflow'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macOS-latest'
      create_report:
        description: 'Choose whether to create and upload the test report'
        required: true
        default: 'no'
        type: choice
        options:
          - 'yes'
          - 'no'
      node_version:
        description: 'Choose the Node.js version for the workflow'
        required: true
        default: '21'
        type: choice
        options:
          - '15'
          - '18'
          - '20'
          - '21'
  schedule:
    - cron: "*/20 * * * *"

jobs:
  qa-automation-api:
    runs-on: ${{ github.event.inputs.os }} 

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2 

    - name: Set up Node.js ${{ github.event.inputs.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ github.event.inputs.node_version }}

    - name: Install dependencies
      run: |
        npm i 

    - name: Run tests
      run: |
        npm test  

    - name: Run report
      if: ${{ github.event.inputs.create_report == 'yes' }}
      run: |
        npm run report  

    - name: Deploy report to GitHub Pages
      if: ${{ github.event.inputs.create_report == 'yes' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git checkout --orphan gh-pages
        git reset
        cp -r ./reports/* .
        git add .
        git commit -m 'Deploy test report to GitHub Pages'
        git push -f "https://${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" gh-pages

    - name: Create URL file
      if: ${{ github.event.inputs.create_report == 'yes' }}
      run: |
        echo "https://${{ github.repository_owner }}.github.io/${{ github.repository }}/" > report_url.txt

    - name: Upload URL as artifact
      if: ${{ github.event.inputs.create_report == 'yes' }}
      uses: actions/upload-artifact@v4
      with:
        name: report-url
        path: report_url.txt
